# Generated by Django 4.0.3 on 2023-04-15 20:46

from django.db import migrations, models
import shortner.Models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300, unique=True)),
                ('new_url', models.CharField(default=shortner.Models.buildstr, max_length=50, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
